- hosts: jobportal
  become: yes
  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Run Job Portal frontend container
      docker_container:
        name: job-portal-frontend
        image: stutigambhir/job-portal-frontend:latest
        state: started
        restart_policy: always
        ports:
          - "80:80"
