- name: Deploy Job Portal Docker container
  hosts: web
  become: true
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true

    - name: Pull the latest Docker image
      command: docker pull stutigambhir/jobportal:latest

    - name: Stop and remove existing Job Portal container (if any)
      shell: docker rm -f jobportal || true

    - name: Run Job Portal container
      shell: docker run -d --name jobportal -p 80:3000 stutigambhir/jobportal:latest
